/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    FooterBg: typeof import('./src/components/home/FooterBg.vue')['default']
    HeroCarousel: typeof import('./src/components/home/HeroCarousel.vue')['default']
    HorizontalPinPanels: typeof import('./src/components/home/HorizontalPinPanels.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollFadeFixPhotos: typeof import('./src/components/home/ScrollFadeFixPhotos.vue')['default']
    ScrollFadeFullScreen: typeof import('./src/components/home/ScrollFadeFullScreen.vue')['default']
    ScrollFadePhotos: typeof import('./src/components/home/ScrollFadePhotos.vue')['default']
    ScrollRevealBlocks: typeof import('./src/components/home/ScrollRevealBlocks.vue')['default']
    ScrollRevealGrid: typeof import('./src/components/home/ScrollRevealGrid.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SlideInSections: typeof import('./src/components/home/SlideInSections.vue')['default']
    StickyFixText: typeof import('./src/components/home/StickyFixText.vue')['default']
    WaterfallHorizontal: typeof import('./src/components/WaterfallHorizontal.vue')['default']
    WaterfallText: typeof import('./src/components/home/WaterfallText.vue')['default']
  }
}
