/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoxReveal: typeof import('./src/components/home/BoxReveal.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HorizontalPanels: typeof import('./src/components/home/HorizontalPanels.vue')['default']
    HorizontalPinPanels: typeof import('./src/components/home/HorizontalPinPanels.vue')['default']
    PhotoFade: typeof import('./src/components/home/PhotoFade.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollFadeFixPhotos: typeof import('./src/components/home/ScrollFadeFixPhotos.vue')['default']
    ScrollFadePhoto: typeof import('./src/components/home/ScrollFadePhoto.vue')['default']
    ScrollFadePhotos: typeof import('./src/components/home/ScrollFadePhotos.vue')['default']
    ScrollFixText: typeof import('./src/components/home/ScrollFixText.vue')['default']
    ScrollRevealBlocks: typeof import('./src/components/home/ScrollRevealBlocks.vue')['default']
    ScrollRevealGrid: typeof import('./src/components/home/ScrollRevealGrid.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SlideInSections: typeof import('./src/components/home/SlideInSections.vue')['default']
    SlideSections: typeof import('./src/components/home/SlideSections.vue')['default']
    StickyCard: typeof import('./src/components/home/StickyCard.vue')['default']
    StickyCenterCard: typeof import('./src/components/home/StickyCenterCard.vue')['default']
    StickyFixText: typeof import('./src/components/home/StickyFixText.vue')['default']
    StickyGrid: typeof import('./src/components/home/StickyGrid.vue')['default']
    WaterfallText: typeof import('./src/components/home/WaterfallText.vue')['default']
  }
}
